namespace BtrieveWrapper
{
    /// <summary>
    /// Btrieve関数のオペレーションを取得する。
    /// </summary>
    public enum Operation : ushort
    {
        Open = 0,
        Close = 1,
        Insert = 2,
        Update = 3,
        Delete = 4,
        GetEqual = 5,
        GetNext = 6,
        GetPrevious = 7,
        GetGreater = 8,
        GetGreaterThanOrEqual = 9,
        GetLessThan = 10,
        GetLessThanOrEqual = 11,
        GetFirst = 12,
        GetLast = 13,
        Create = 14,
        Stat = 15,
        SetDirectory = 17,
        GetDirectory = 18,
        BeginTransaction = 19,
        BeginSharedTransaction = 1019,
        EndTransaction = 20,
        AbortTransaction = 21,
        GetPosition = 22,
        GetDirect = 23,
        StepNext = 24,
        Stop = 25,
        Version = 26,
        Unlock = 27,
        Reset = 28,
        SetOwner = 29,
        ClearOwner = 30,
        CreateIndex = 31,
        DropIndex = 32,
        StepFirst = 33,
        StepLast = 34,
        StepPrevious = 35,
        GetNextExtended = 36,
        GetPreviousExtended = 37,
        StepNextExtended = 38,
        StepPreviousExtended = 39,
        InsertExtended = 40,
        ContinuousOperation = 42,
        GetByPercentage = 44,
        FindPercentage = 45,
        UpdateChunk = 53,
        GetEqualKey = 55,
        GetNextKey = 56,
        GetPreviousKey = 57,
        GetGreaterKey = 58,
        GetGreaterThanOrEqualKey = 59,
        GetLessThanKey = 60,
        GetLessThanOrEqualKey = 61,
        GetFirstKey = 62,
        GetLastKey = 63,
        StatExtended = 65
    }
}
